fixing nohup

diff --git a/Jenkins/Jenkinsfile-kaniko b/Jenkins/Jenkinsfile-kaniko
--- a/Jenkins/Jenkinsfile-kaniko
+++ b/Jenkins/Jenkinsfile-kaniko
@@ -1,6 +1,12 @@
 pipeline {
     agent { label 'ecs-fargate-agent' } 
 
+        options {
+        // Disable Jenkins' default process handling
+        durabilityHint 'PERFORMANCE_OPTIMIZED'
+        disableConcurrentBuilds()
+    }
+
 
     environment {
         SONAR_HOST_URL = "http://44.223.29.212:9000/"
@@ -10,6 +16,7 @@ pipeline {
         FRONTEND_ECR_REPOSITORY = "techcloud-academy-frontend-apps"
         BACKEND_ECR_REPOSITORY = "techcloud-academy-backend-apps"
         FRONTEND_ECR_NGING_REPOSITORY ="techcloud-academy-frontend-apps-nginx-proxy"
+        PATH = "/usr/local/bin:/usr/bin:/bin:/kaniko:/trivy/bin:${env.PATH}"
     }
 
     stages {
@@ -130,7 +137,7 @@ pipeline {
             }
         }
     }
-
+/*
      stage('Docker Build & Push frontend to ECR with Kaniko') {
     steps {
         script {
@@ -153,7 +160,7 @@ pipeline {
             }
         }
     }
-    /*
+    
          stage('Docker Build & Push frontend nginx proxy to ECR with Kaniko') {
     steps {
         script {
@@ -180,6 +187,15 @@ pipeline {
             stage('Trivy Image Scan') {
             steps {
                 script {
+                                        // Diagnostic commands
+                    sh '''
+                        trivy --version
+                        echo "=== Environment Diagnostics ==="
+                        echo "PATH: $PATH"
+                        which trivy || echo "Trivy not found in PATH"
+                        which nohup || echo "nohup not found in PATH"
+                        echo "============================="
+                    '''
              // Scan frontend nginx proxy image in ECR
             sh """
             trivy --version
